### ISSUE TITLE
Playlist kaputt, nagut funktioniert nicht 100%

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#1]
damit wir hier mal den 1. Bug haben ;-)

seit gestern springt er bei mir nicht mehr von einem Podcast zum nächsten sondern hört einfach auf, obwohl die Playlist gut gefüllt ist.

Das kann auch wenig mit Hintergrundaktivität zu tun haben, weil das auch ist wenn ich den Podcast erst vor <5min angemacht habe.

**Comment by nosyjoe** [comment]
ja sehr gut, danke dir dafür. Springt er nie weiter? Oder nur manchmal nicht?

**Comment by EagleEyeBW** [comment]
gestern und heute gar nicht, da gabs 2 oder 3 Podcast Übergänge
Ach möglicherweise könnte es daran liegen dass der Folgepodcast schon gestartet wurde (~30%)

**Comment by EagleEyeBW** [comment]
also der Übergang zu einem neuen Podcast d.h. der noch nicht gestartet wurde geht problemlos, denke dass da das Problem liegt

**Comment by nosyjoe** [comment]
ok das klingt nach einem  guten Ansatzpunkt, danke dir für die Analyse :)

**Comment by nosyjoe** [comment]
hier sollte auch die 1.4 abhilfe schaffen. playlist-handling ist hier komplett neu

**Comment by EagleEyeBW** [comment]
ich bin mir nicht sicher wo genau der Fehler liegt, aber um die Playlist hakts immer noch etwas.
- Ich hab eine sehr volle Playlist
- 1. Eintrag ist zu teilen angehört
- Ich bin aber zum 5. gesprungen und hab angefangen da anzuhören
- Beim Fortsetzen nach der täglichen Pause will er teilweise aber den 1. fortsetzen statt den 5.

**Comment by nosyjoe** [comment]
old -> closed
