### ISSUE TITLE
Player geht nicht auf obwohl Playlist gefüllt ist

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#10]
ich habe eine gefüllte Playlist und will auf den Player wechseln, aber er poppt nur kurz auf und verschwindet dann wieder (keine aktive Wiedergabe)

**Comment by nosyjoe** [comment]
weisst du, wie das passiert? ich kann das nicht nachstellen. hörst du die letzte episode auf der playlist bis zum ende?

**Comment by EagleEyeBW** [comment]
ja das wird wohl an meiner Art liegen :D
ich hab ne laaaange Playlist und ab und zu spiele ich Podcasts ab die nicht in der Playlist sind, ich glaube dann tritt das vermehrt auf

**Comment by nosyjoe** [comment]
ok lange playlist hab ich auch, so 10-20 episoden :) 
ok, ich hab nen verdacht, woran das liegt. Episoden, die du abspielst und die noch nicht in der Playliste sind, sollten immer auch in die Playliste hinzugefügt werden. Manchmal geht das schief, das kann ich im Crashlytics error logging sehen. Weiss aber noch nicht genau, warum. Damit könnte das Problem zusammenhängen.

**Comment by EagleEyeBW** [comment]
mein Vorschlag, mach doch einfach ne Beta App die jeden Scheiß trackt und dir schickt, jeden klick + Navigation ggf dazu loggen, was eigentlich passieren sollte wie jetzt hier
musst sie ja nicht live machen

**Comment by EagleEyeBW** [comment]
ich hab gestern etwas bemerkt, aufs Cover hämmern hat nix gebracht, aber aufklappen und auf das Playicon hatte funktioniert.
Ich werde das mal beobachten

**Comment by nosyjoe** [comment]
äh, ich bin verwirrt :) wenn du im home screen in der playlist auf das cover tappst, geht doch nur die action bar auf und zu? Play/Pause tut es da gar nicht. 🤔

**Comment by EagleEyeBW** [comment]
stimmt jetzt bin ich auch verwirrt, warum ist dann da nix aufgegangen. Ok vergiss die Aussage einfach, ich hab den Verdacht dass ich da wohl mehr kaputt gemacht habe :D --> siehe Ticket was gleich aufpoppt :D

**Comment by EagleEyeBW** [comment]
aktuell ist es kaum noch aufgetreten

**Comment by nosyjoe** [comment]
Mache ich zu, einfach wieder-öffnen falls der wiederkommt
