### ISSUE TITLE
Gerade häufig defekte Downloads laut Meldung

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#11]
Ich hab in den letzten beiden Tagen etwas häufiger die Meldung bekommen dass die Daten nicht ganz ok sind und ein neuer Download helfen würde.

Das irgendwie verdächtig häufig, bei 3 oder 4 Dateien.

**Comment by nosyjoe** [comment]
nabend! kannst du mir schreiben welche? oder gibt's sonst irgendwelche anhaltspunkte? wie voll ist denn dein speicher? hattest du immer wlan?

**Comment by EagleEyeBW** [comment]
ich bin mir übers WLAN nicht sicher, ich bin mir wegen dem anderen Fehler auch nicht 100%ig sicher ob ich sie lokal oder ausm Netz geladen hab.
Ich hab das hauptsächlich bei der https://www.bbc.co.uk/programmes/p083t547
bei den ersten 5 Teilen (inkl Teaser & Co)

Laut Handy sind 70gig frei

**Comment by nosyjoe** [comment]
sollte gefixt sein in der 1.4.5
