### ISSUE TITLE
Download Icon ändert sich nicht

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#12]
wenn ich auf Download klick ändert sich nichts 
aber ich seh dass sie heruntergeladen wird

**Comment by EagleEyeBW** [comment]
ok nach app kill gehts

**Comment by nosyjoe** [comment]
also es dauert manchmal ein paar sekunden, bis sich der button updated. aber ich schätze so lange hast du gewartet vor'm killen?

**Comment by EagleEyeBW** [comment]
jap

**Comment by nosyjoe** [comment]
ich mach das hier mal zu, auch wenn das "nach dem app killen geht's" nicht das beste ergebnis ist ;)
