### ISSUE TITLE
Playlist Fortschritt stimmt nicht 

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#13]
In der letzten DB von mir hast du eine 13min To The Moon Episode mitten in den anderen oder die 1. in der längeren Reihe von Folgen. Deren Darstellung in der Playlist stimmte nicht, kaum bin ich auf die Episode gegangen und hab sie abgespielt sprang sie auf die echte Zeit.

etwas ähnliches hatte ich heute noch einmal, Ich dachte ich hätte eine Folge schon angehört, aber trotzdem gestartet und er sprang direkt in die nächste Episode wo ich gestern aufgehört hatte

**Comment by nosyjoe** [comment]
ok ich guck mir das morgen mal genauer an
