### ISSUE TITLE
Episode -> Download -> Sie verschwindet

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#14]
Ich bin mir nicht sicher ob es ein Bug ist oder Feature, wenn ich bei einer Episode auf Download klick verschwindet sie ausm "Posteingang"

ich fände es besser wenn sie dort bleibt

**Comment by nosyjoe** [comment]
Naja das ist ein Feature, aus konsistenzgründen auch beim Download. Alle Aktionen auf einer episode entfernen sie aus der inbox - du kannst halt in den Settings generell umschalten, ob Aktionen aus der inbox entfernen oder nicht, aber nur für Downloads deaktivieren geht nicht

**Comment by EagleEyeBW** [comment]
ja ich finds etwas komisch, wenn ich halt "Ich will sie mal runterladen weil ich sie gleich anhören will, aber in die Playlist muss sie nicht" 
und dann muss ich erst den Podcast suchen und darin dann die Episode

**Comment by EagleEyeBW** [comment]
aber dann würde ich das mal als Featurerequest einreichen 😄

**Comment by nosyjoe** [comment]
alternativ kannst du auch auf's "Meins"-Tab wechseln und dort unter downloads gucken
