### ISSUE TITLE
FR: Podcast + Veröffentlichtsdatum in den Infos

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#15]
in den Shownotes wäre es schön wenn die Infos noch mit drin stehen, ab und zu fragt ich mich von wann der ist und auf die schnelle sehe ich das nicht

**Comment by nosyjoe** [comment]
👍 hat schon mal jemand angefragt, super Idee

**Comment by nosyjoe** [comment]
umgesetzt in version 1.4.6
