### ISSUE TITLE
Miniplayer(Lockscreen) setzt nicht fort

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#16]
Nach meinem aktuellen Beobachtungsstand:
* Folge anhören
* Folge stoppen
* nach einer Pause eine andere Folge komplett hören, welche nicht in der Playlist ist (in meinem Fall Was jetzt?)
* Player stoppt von allein (passt)
* jetzt über den Miniplayer(Lockscreen) einfach den Playbutton drücken
* Farbe/Darstellung des Miniplayers wechselt auf das neue Aussehen (passt)
* Player startet aber die letzte Folge von neuem statt wo man aufgehört hat

**Comment by EagleEyeBW** [comment]
ok ich kanns zu 100% nachstellen, es ist nur ein Folgebug

Wenn ich unter dem Lockscreen eine Folge beende sehe ich im Player ja nicht den aktuellen Zeitlichen Zustand der nächsten Folge.
Bisher habe ich es nur für einen Darstellungsfehler gehalten, weil wenn ich im normalen Player auf Play gedrückt hab sprang er dann auf die richtige Stelle, aber jetzt im Miniplayer leider nicht.

**Comment by nosyjoe** [comment]
Moin. Also zu dem ursprünglichen Bug: Die Episode sollte natürlich nicht von neuem beginnen.

Hab noch Fragen. 

Aber erst mal zur Klärung der Situation. In den Settings kann man einstellen, an welcher Stelle eine Episode in die Playliste hinzugefügt wird: Am Ende (default), nach der aktuellen Episode (mein favorite) oder am Anfang.

Der Default ist hier eben am Ende der Playlist. Kannst du mal gucken, auf was das bei dir gestellt ist (ganz oben on den Einstellungen)?

Wenn du in der Inbox auf "Play" drückst, kommt die Episode auf die Playlist, eben an die konfigurierte Stelle (nehme mal an das ist am Ende). Wenn die Episode dann vorbei ist, endet auch das Playback, weil die playlist am Ende angekommen ist. Wenn du im Miniplayer auf Play gehst, sollte dann die Playliste von vorne Spielen und das Playback mit der ersten Episode starten. Das allerdings schon an der Position, an der du vorher mal aufgehört hattest. 

Soweit das, makes sense?

Wenn ich mir überlege, wie du den Episoden-Play-Button vertstehst, macht es evtl. Sinn, wenn man drauf drückt, die Episode _vor_ der aktuellen Episode einzuordnen und zu starten, damit es danach mit der Playlist an der Stelle weitergeht, wo man war. Ich mach dazu mal ein Ticket #17

**Comment by EagleEyeBW** [comment]
ok Begriffsklärung: "Letzte Folge" letzte die ich angehört hatte bevor ich die außerplanmäßige gestartet hab, diese Folge war auch am Anfang der Playlist

Ich sortiere unten in die Playlist ein

**Comment by nosyjoe** [comment]
k danke für das update

**Comment by EagleEyeBW** [comment]
Also nur ums noch einmal klar zu sagen, der Fehler ist dass er vom Start der Folge los geht und nicht die zuletzt aufgehörte Position

**Comment by nosyjoe** [comment]
ok, hab den bug gefixt. kommt bald eine 1.4.7er version!
