### ISSUE TITLE
Download Liste enthält viel zu viele Elemente

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#19]
in der Download Liste sind jede Menge Einträge bei mir wogegen in der Playlist kaum Elemente sind.
ich vermute dass da irgendwie nicht sauber gelöscht wird
![image](https://user-images.githubusercontent.com/3194885/118764015-1783cf80-b879-11eb-8283-7c19be3fad24.png)
![image](https://user-images.githubusercontent.com/3194885/118764028-1c488380-b879-11eb-8518-aa91e6ab7d95.png)

Interessanterweise primär alte Einträge

**Comment by nosyjoe** [comment]
Danke für's melden. Ich habe mal ein paar Tests gefahren mit der aktuellen 1.4.8er Version, und da haben sich die Downloads nach dem eine Episode fertig gehört wurde, korrekt entfernt. Hab eine ganz Playlist durchrattern lassen, sieht so aus als wäre das Problem in einer älteren Version gewesen. 

Das kann durchaus sein, da hatte ich mal Probleme :)

Wenn die Downloads neueren Datum sind und nicht korrekt gelöscht, dan kann es eventuell auch sein, dass du sie manuell von der Playlist gelöscht wurden. Dann wird der Download nämlich nicht automatisch mitgelöscht.
