### ISSUE TITLE
Player hat vergessen was er abspielen soll

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#2]
Ich habs immer wieder dass der Player nichts enthält was ich früh abgespielt hab, dann muss ich immer auf die Playlist zurück und es dort starten.

Meistens ist es wenn ich >7h zwischen Stopp und wieder abspielen hab. 
Ich hab auch einen gewissen Zusammenhang zwischen Miniplayer (Notifications) und dem Reset des Player festgestellt, d.h. wenn der Miniplayer weg ist aus den Notifications ist oftmals auch der Player wieder leer.

**Comment by nosyjoe** [comment]
sollte in der 1.4.0,94 beta gefixt sein

**Comment by EagleEyeBW** [comment]
hmmmm ich glaube das ist noch nicht gefixt
Gestern hattte ich das Phänomen das der Player auf einmal dachte er müsste das 1. in der Playlist abspielen obwohl ich das 2. abspiele
Und heute früh hatte er wieder vergessen was er abspielen muss


Ich beobachte aber mal weiter

**Comment by EagleEyeBW** [comment]
Ne klappt leider nicht 
![Screenshot_20210119-140832](https://user-images.githubusercontent.com/3194885/105089701-c1a34480-5a9d-11eb-83b0-e32ee26f48fd.jpg)
![Screenshot_20210119-140846](https://user-images.githubusercontent.com/3194885/105089724-c667f880-5a9d-11eb-97d5-dd76f26f7a0b.jpg)

er vergisst was er abspielen soll, aber bei den Infos ists richtig, gibts mehr Infos die ich dir geben kann?

**Comment by nosyjoe** [comment]
hmpf! was hast du denn für ne version? steht in den einstellungen ganz unten.

und: wenn du die episode spielst, pausierst, die app im app-switcher killst und dann neu startest - ist das dann der gleiche effekt?

**Comment by EagleEyeBW** [comment]
Version: 1.4 (14094) Hash 36beacc6

ne wenn ich sie kill behält er alles

**Comment by nosyjoe** [comment]
Sehr seltsam! 

Verändert sich sonst noch was, an der Playliste z.B.? Also ist die anders, ist die Abspielposition anders?

Wie beendest du das abspielen abends? Machst du manuell auf Pause? Oder trennst du zum Beispiel einfach die Bluetooth-Verbindung?

**Comment by EagleEyeBW** [comment]
das war heute Mittag <-> Abend, da trenn ich einfach nur Bluetooth (Auto aus)
Ich glaube die Position passt, aber ich hab schon Tage gehabt wo ich der Meinung bin er ist noch länger gelaufen als Bluetooth da war

**Comment by EagleEyeBW** [comment]
also heute wieder gehabt, gaaanz komisch.
Der Player weiß nicht was er machen soll, in der Info Box ist alles enthalten
Und vorallem, ich kann über die Playlist den Podcast nicht wieder starten, ich muss erst einen anderen starten und dann kann ich den anderen wieder starten. Er macht dann auch an der alten Stelle weiter.

**Comment by nosyjoe** [comment]
ok danke für deinen weiteren Input. Ich gehe davon aus, dass der Fehler im Zusammenhang mit dem Bluetooth steht. Irgendwie kommt da ein kaputter State zustande. Du hattest den Miniplayer in den Notifications erwähnt. Der geht weg, wenn der Service beendet wird, und damit die ganze App. Das ist normal, wenn grade nix abgespielt wird kann das durchaus passieren. Muss nicht, aber kann.

Also wäre der Flow Spielt auf Bluetooth-Gerät -> Bluetoothgerät ausgeschaltet (einfach weg), Player pausiert, aber Service & App laufen noch -> App wird nach einiger Zeit beendet -> du öffnest die App wieder und der Player ist leer. Kommt das hin?

Das kann ich mal mit meinem BT-Lautsprecher nachstellen.

**Comment by EagleEyeBW** [comment]
also heute liefs problemlos

ich werde mal gucken dass ich jetzt in den nächsten Tagen etwas genauer rumteste

**Comment by EagleEyeBW** [comment]
mit der Alpha komm ich wieder drauf aber er hatte vergessen was er abspielen soll


ein andermal hab ich einen Podcast abgespielt der nicht in der Playlist war und dann war im Player der 1. aus der Playlist drin 👍 
Aber ich glaube die Zeitachse stammte vom zuletzt abgespielten zu einem Zeitpunkt wo der Player zuletzt im Vordergrund war

**Comment by EagleEyeBW** [comment]
aktuell immer noch vorhanden

**Comment by nosyjoe** [comment]
so also kommt das noch vor bei dir @EagleEyeBW ? Habe da noch einen Fix eingebaut bei der 1.5.1

**Comment by EagleEyeBW** [comment]
aktuell nicht mehr

**Comment by nosyjoe** [comment]
seems to be fixed
