### ISSUE TITLE
Playlisteinträge verschwinden

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#22]
V 15033

- Ich hab eine gut gefüllte Playlist
- der 1. Eintrag ist schon weit abgespielt (aber läuft gerade nicht)
- im Posteingang kommt eine neue Folge rein, ich drück auf Play damit sie oben hinzugefügt wird, stoppe aber direkt nachdem ich es kann weil ich sie nicht abspielen will
- einige Zeit später gibts ne neue andere Folge (Was jetzt?) im Posteingang, --> Play
- nach dem die Was Jetzt Folge vorbei ist geht es nicht zu der anderen Folge die ich vorher hinzugefügt hab sondern überspringt diese und macht direkt bei der letzten richtig abgespielten weiter (die aus Punkt 2)

**Comment by nosyjoe** [comment]
@EagleEyeBW kann ich mit deiner DB nicht reproduzieren :-(

**Comment by EagleEyeBW** [comment]
ok ich versuche das morgen früh noch einmal zu reproduzieren

**Comment by nosyjoe** [comment]
Bitte wiedereröffnen wenn noch aktuell
