### ISSUE TITLE
keine Infos über neue Episoden

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#23]
ich hab vor Wochen/Monaten ka (kennst ja meine DB ;-) ) GeePaw Hill hinzugepackt und gerade festgestellt dass jede Woche eine neue Episode kam und ich hab nie etwas davon mitbekommen.

**Comment by nosyjoe** [comment]
Moin. Also hier kommen 2 Bugs zusammen: 
 1. vom Backend kommen für die iTunes-Id (1484418432) keine neuen Folgen
 2. Beim manuellen Laden (Meine -> Podcasts -> GeePawHill) gibt es eine Race-Condition, die die Anzeige in der Inbox verhindert)

**Comment by nosyjoe** [comment]
ok nachfrage an dich @EagleEyeBW: Tauchen die Episoden in der Inbox auf, wenn du auf den Podcast gehst (und dort nichts mit den neuen Episoden machst)?

**Comment by EagleEyeBW** [comment]
jetzt nachdem ich das festgestellt habe sehe ich in meiner inbox neue einträge

**Comment by nosyjoe** [comment]
@EagleEyeBW ist das eigentlich noch aktuell?

**Comment by EagleEyeBW** [comment]
ich denke es ist alles gefixt
