### ISSUE TITLE
Episodes able to add multiple times and removes all

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#27]
I could add an episode multiple times and when I pressed "remove from Playlist" all removed instead of only one

**Comment by EagleEyeBW** [comment]
an Update, today I got the same issue, but I didn't added the episode two times.
The episode occoure two times after moving in the playlist. (from bottom to 2nd entry)

**Comment by nosyjoe** [comment]
hmm, is this maybe a display bug? Could you restart the app next time this happens and see if this fixes it? I think I have seen this happen. 

PS: Why english now? :)

**Comment by EagleEyeBW** [comment]
jep display issue regarding reorder

because your tickets are english ;)
