### ISSUE TITLE
Player zeigt falsche Zeit an

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#3]
Der Player zeigt bei der aktuellen alles gesagt "Richard Socher" die falsche Spielzeit an
Laut Anzeige sollen es nur 14s sein

**Comment by nosyjoe** [comment]
Diese hier oder? https://www.zeit.de/digital/2020-11/richard-socher-kuenstliche-intelligenz-interviewpodcast-alles-gesagt
Der Web-Player bei Zeit zeigt auch nicht das richtige an, da ist bei 24s Schluss

**Comment by EagleEyeBW** [comment]
jap genau, jaja immer auf die anderen schieben ;)
Ja ok dann müssen es wohl die Daten sein, wollte es nur schnell erfassen bevor ich es vergesse daher hab ichs nicht überprüft

**Comment by nosyjoe** [comment]
achso, nee so meinte ich das gar nicht, kann ja sein, das beide Player ein Problem haben. Kann natürlich auch die Datei sein, aber das würd ich schon noch auschecken, ich mach's mal wieder auf hier

**Comment by EagleEyeBW** [comment]
👍 passt :)

**Comment by EagleEyeBW** [comment]
ach ich hab mir die Episode jetzt angehört, es war ein aufgezeichneter Livestream daher fehlt wahrscheinlich die Dauer in der Datei
Aber interessanterweise wurde die Datei danach nicht gelöscht obwohl er zum nächsten Beitrag übergesprungen ist
