### ISSUE TITLE
Bug: New episode not added to top

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#32]
When I start a new episode from inbox or feed, it is mostly not added right to the top.
Currently most time it is added as second entry

**Comment by nosyjoe** [comment]
There's two different variants of this. If you add from Inbox via the "Play" button of the episode, the episode is placed before the currently playing episode in the playlist. 

If the add to playlist button is used, the position the episode is added depends on the setting of Preference > Playback > Add to Playlist..., can be one of Start, End, after currently playing

which button did you push and what's your "Add to Playlist..." setting?

**Comment by KayGestalten** [comment]
as it is 1.5 years ago, killit :D

**Comment by nosyjoe** [comment]
😂
