### ISSUE TITLE
Kein automatische Info für neue Episoden

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#4]
Damit wir es hier auch drin haben ;-)
Nach ~5 Tagen nicht nutzen der Anwendung gabs leider keine Info über eine gestern erschienene neue Episode. Erst nach öffnen poppte sie auf. (One Plus 8, mit Android 11)

App ist auch explizit von der Akku Optimierung ausgeschlossen

**Comment by nosyjoe** [comment]
siehe Probleme Corona-Warn-App ;)
