### ISSUE TITLE
Setting Abspielgeschwindigkeit doesn't work 

### ISSUE THREAD

**Issue by graphcon** [nosyjoe/procast-tickets#40]
Setting Abspielgeschwindigkeit jumps back when to 1x when overlay is closed. Also, there is no hearable difference between speeds. I guess, it's not working 🤷🏾‍♂️

Steps to reproduce:
1. Start playing an episode
2. Try to set Abspielgeschwindigkeit
=> not working

Can't attach video because screencast is 40 MB but Github only allows 10MB

**Comment by nosyjoe** [comment]
will be fixed in 1.7.3

**Comment by graphcon** [comment]
This issue is not fixed. See my WhatsApp message
