### ISSUE TITLE
Player plays wrong episode

### ISSUE THREAD

**Issue by nosyjoe** [nosyjoe/procast-tickets#42]
Strps to reproduce:

1. Add an episode to the playlist via My -> Podcasts -> Episode list
2. Open the Player
3. Tapping "Play" plays the wrong episode

**Comment by nosyjoe** [comment]
Unfortunately, I can't reproduce this issue. Need more info (video, sqlite db).

**Comment by tehael** [comment]
After deleting all previously downloaded episodes that issue is gone.

**Comment by nosyjoe** [comment]
can this be closed then?

**Comment by tehael** [comment]
Yep! I would have if I could.
