### ISSUE TITLE
Earphone interaction not working anymore

### ISSUE THREAD

**Issue by tehael** [nosyjoe/procast-tickets#44]
I think since v1.8.0 on Android the jumping back and forward within an episode using the corresponding interaction with my earphones (i.e. double-click left/right for back/forward) is broken.

Initially I was thinking that might be an issue with the hardware, but testing the interaction in other audio app (e.g. Spotify) showed that the hardware interaction is working as intended.

**Comment by nosyjoe** [comment]
will check this!

**Comment by nosyjoe** [comment]
fixed in 1.8.1
