### ISSUE TITLE
Automatisches löschen von Downloads 

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#5]
Ich habe seen Verdacht das die Begrenzung auf "nicht in der Playlist" nicht funktioniert 
![Screenshot_20201212-093053](https://user-images.githubusercontent.com/3194885/101979360-de598a80-3c5c-11eb-8a13-8f6dacbed535.jpg)

Ich habe mehrere Dinge direkt in die Playlist gepackt und herunter geladen
Aber nach einiger Zeit sind die Downloads gelöscht

**Comment by nosyjoe** [comment]
danke dir! ich check das. die nächsten wochen müsst ich dann mal dazu kommen

**Comment by nosyjoe** [comment]
das sollte auch in der aktuellen beta von der 1.4.0 gefixt sein

**Comment by EagleEyeBW** [comment]
ich bin mir nicht soooo ganz sicher, ich hab den Verdacht dass mit den Downloads was nicht ganz rund läuft. Weil einige haben bei mir kein "Bin offline" Icon 
und andere hab gerade erst gemerkt dass sie herunter geladen werden sollen


man muss aber auch sagen meine Playlist ist sehr lang :D

**Comment by nosyjoe** [comment]
hmm..versteh ich nicht ganz! bin offline-icon? also, bei normaler einstellung werden podcasts nur im wlan geladen. wenn du den download ohne wlan startest, kommt der lade-kringel. wenn du dann ins wlan gehst, sollte der download starten. wenn du während des downloads wlan ausmachst, kommt ein ausrufezeichen download pausiert.

erklärt das teile oder alles?

**Comment by EagleEyeBW** [comment]
ohhh wie passend 
gerade wollte ich dir beschreiben was ich hab und es hat sich wieder geändert 

ich hab def einige Podcasts heruntergeladen gehabt, ich weiß gerade nicht mehr genau welche das waren und jetzt hat nur noch einer die Wolke mit Pfeil runter dran (in der Playlist)
Wenn ich mir die Details anseh (aufklappe) dann ist bei allen auch das Herunterladen Icon da, beim letzten mal kamen dann einige auf die Idee dass runtergeladen werden soll

die App ist aktuell auch angeblich 40mb groß, 44.34mb Nutzerdaten und  aber 327mb Cache, ich schickt dir mal meine DB

**Comment by EagleEyeBW** [comment]
aktuell keinerlei Probleme mehr 👍

**Comment by nosyjoe** [comment]
Download-Management wurde überarbeitet von 1.4.3 -> 1.4.4:

Die App beauftragt den Android DownloadManager, die Media-Dateien in den [App-Downloads-Ordner](https://developer.android.com/reference/android/os/Environment#DIRECTORY_DOWNLOADS) zu laden (external files wenn verfügbar, fallback internal wenn nicht).

Nach abgeschlossenem Download wird die Datei nach `Environment#DIRECTORY_PODCASTS` verschoben und der DownloadManager-Eintrag entfernt.

Der Bug trat auf, weil der DownloadManager wohl (auch Hersteller-unterschiedlich und API-Level abhängig) Downloads nach gewisser Zeit löscht, wenn man die Datei nicht verschiebt.

**Comment by EagleEyeBW** [comment]
Öhm bad news

![Screenshot_20210316-164808](https://user-images.githubusercontent.com/3194885/111338980-ac026380-8677-11eb-847f-b4bf48aa417c.jpg)
![Screenshot_20210316-164801](https://user-images.githubusercontent.com/3194885/111338987-ac9afa00-8677-11eb-861f-c8dd3f51ed33.jpg)
