### ISSUE TITLE
History wurde vor einigen Wochen gelöscht 

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#6]
gerade hab ich festgestellt dass mir die History bis vor ~1 Monat abhanden gekommen ist

**Comment by nosyjoe** [comment]
hi, wie schon beschrieben ist das ein Feature _gewesen_, also bis zur version 1.3.4. inklusive. Mit 1.4.0 sollte das nicht mehr passieren.
