### ISSUE TITLE
Episodenliste lässt sich nicht mehr Scrollen unter bestimmten Bedingungen

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#7]
Reproduktion:
 - Gehe in die Episodenliste zb von Minkorrekt
 - Scroll paar Seiten runter
 - In die Info gucken
 - zurück gehen
 - bisschen "flackern" weil paar Dinge aus der Liste fliegen und man kann nicht mehr nach unten scrollen

**Comment by nosyjoe** [comment]
Danke für den Bug-Report!
Sollte in der neuen Beta (1.4.0.105) gefixt sein.

**Comment by EagleEyeBW** [comment]
👍 sieht gut aus
