### ISSUE TITLE
Probleme beim Wechsel von Podcasts, welche meistens auftreten wenn der 1. nicht in der Playlist ist

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#8]
Heute hab ich das Phänomen gehabt, dass das Bild aus dem vorhergehenden Podcast im darauffolgenden noch angezeigt wurde.
Das Bild vom alten war ein Bild was beim Abspielen eingeblendet wurde, also nicht das allgemeine Logo

**Comment by nosyjoe** [comment]
ok danke! das kommt noch hin und wieder vor, ist mir auch schon aufgefallen, grmbl.

**Comment by nosyjoe** [comment]
bzw. moment, ist das noch aktuell?

**Comment by EagleEyeBW** [comment]
ich werde das mal beobachten, weil ich glaub vor 20 Tagen gabs die aktuelle Version noch nicht

**Comment by EagleEyeBW** [comment]
also Bild passt jetzt immer nur der Fortschritt nicht.
Ich hab den Verdacht dass es damit zusammen hängt dass man den Podcast im Hintergrund hört und er da aus läuft.
Weil die Tage als ich aktiv in der App war um das zu beobachten passte der Fortschritt


ABER, ich hab heute ein neues Phänomen gehabt. Ich hatte noch 2 halb angehörte "Was jetzt?" Podcasts die NICHT in der Playlist waren. Die hab ich mir angehört (über die Episodenliste) und nach jedem Ende hat er irgendeinen der letzten Podcasts aus meiner Playlist gestartet. Aber nach jeder einen anderen (einmal den vorletzten und dann den letzten)

ich bennen mal das Ticket hier um ;)

**Comment by nosyjoe** [comment]
Naja, also das ist folgendermaßen: Wenn du auf den Play-Button in der Episodenliste tippst, wird die Episode schon auch zur Playlist hinzugefügt. Standardmäßig am Ende der Playlist (lässt sich aber in den Einstellungen konfigurieren). *Zusätzlich* wird auch sofort das Abspielen gestartet. 

Wenn du danach andere Episoden zur Playlist hinzufügst, werden die dahinter auf der Playlist einsortiert.

**Comment by EagleEyeBW** [comment]
ahhhhh ja gerade angeguckt 👍 alles klar mein Fehler

**Comment by nosyjoe** [comment]
👍  dann mach ich das mal zu. merke mir aber, dass das mit dem "Play" und der Zusammenhang zur Playlist unklar ist.
