### ISSUE TITLE
Kann Podcast erst nach viel auf unterschiedlichen Podcasts klicken starte

### ISSUE THREAD

**Issue by EagleEyeBW** [nosyjoe/procast-tickets#9]
so heute wurde es richtig interessant
Podcast 1 wurde gestern gehört, heute früh wollte ich aber mit Podcast 2 starten.
- Er hatte es wieder vergessen was zuletzt war
- Klick auf Podcast 2
- Aber statt dass er startet ging der Player kurz an und wieder aus
- nach klick auf Podcast 1 ging der Player auch direkt wieder aus
- Klick auf Podcast 2 nix
- Klick auf Podcast 1 und es lief dann

**Comment by EagleEyeBW** [comment]
ist wie #10 schon einige ZEit nicht mehr aufgetreten

**Comment by nosyjoe** [comment]
ok, closed for now.
